# Generated by Django 3.2.9 on 2021-11-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20211113_1749'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient',
        ),
    ]
