# Generated by Django 3.2.9 on 2021-11-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_remove_ingredient_unique_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='foodgram.RecipeIngredient', to='foodgram.Ingredient', verbose_name='Ингридиенты рецепта'),
        ),
    ]
